name: Staging

on:
  push:
    branches: [ develop ]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to sataging
        run: echo "Staging deployment"
